---
- name: rabbit used by openstack and monitoring
  hosts: controller
  roles:
    - rabbit

- hosts: all
  roles:
    - common

- name: replicated db setup
  include: playbooks/percona.yml

- name: nova code and config
  hosts: controller:db:compute
  roles:
    - memcached
    - nova-common

- name: neutron code and config
  hosts: controller:db:compute:network
  roles:
    - neutron-common

- name: glance code and config
  hosts: controller:db
  roles:
    - glance-common

- name: keystone code and config
  hosts: controller:db
  roles:
    - memcached
    - keystone-common

- name: cinder code and config
  hosts: controller:db:compute
  roles:
    - cinder-common

- name: dbs, db users, db schema updates
  hosts: db[0]
  roles:
    - db

- name: openstack controller services
  hosts: controller
  roles:
    - rabbit
    - client
    - horizon
    - controller
    - memcached

- hosts: compute
  roles:
    - compute
    - cinder-volume

- hosts: network:compute
  roles:
    - openvswitch

- name: openstack network services
  hosts: network
  roles:
    - network

- hosts: controller[0]
  roles:
    - openstack-setup

- name: Install monitoring
  include: playbooks/monitoring.yml
