---
- include: ucarp.yml

- apt: pkg={{ item }}
  with_items:
    - dnsmasq
    - dnsmasq-utils

- name: ovs ex bridge
  ovs_bridge: name=br-ex state=present

- template: src=etc/init/{{ item }}.conf dest=/etc/init/{{ item }}.conf
  with_items:
    - neutron-l3-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent

- service: name={{ item }} state=started
  with_items:
    - neutron-l3-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent

